name: Brain Beats Blog | Brainwave Entrainment
description: Brain Beats - Free online brainwave entrainment generator for binaural beats, isochronic tones, solfeggio frequencies, and ambient noise.
markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true
  input: GFM
  syntax_highlighter_opts:
    disable : true

permalink: /blog/:year/:month/:day/:title.html
url: "https://brain-beats.in"
baseurl: ""
repository: Mr-Kumar-Abhishek/brain-beats-blog

paginate_path: "/blog/blog/page:num/"
paginate: 5
future: false
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

exclude: ["node_modules", "package-lock.json", "blog/css/main.scss", "scratch", "Gemfile", "Gemfile.lock", "tests", "workbox-config.js", ".github", "DEVELOPMENT.md", "TEST_REPORT.md", "CONTRIBUTING.md", "cocomo-cost-estimate.md", "README.md", "LICENSE.txt", "LICENSE-CONTENT.txt"]
